Using Numpy Array and some of its functions

In [3]:
import numpy as np

my_list = [2,3,4,6]

In [4]:
np.array(my_list)

array([2, 3, 4, 6])

In [5]:
np.arange(0, 12, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [7]:
np.random.rand(5) #0-1

array([0.04575461, 0.81773349, 0.36925763, 0.26558817, 0.70141299])

In [8]:
np.random.randint(1, 100, 10)

array([83, 41,  6,  2, 55, 96, 34,  6, 11, 14])

In [9]:
arr = np.arange(25)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr_rand=np.random.randint(1,50,10)

In [12]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
arr_rand

array([19, 42, 18, 39, 14, 44, 43, 36, 32, 19])

In [15]:
arr_rand.max()

44

In [16]:
arr_rand.min()

14

In [18]:
arr_rand.argmax() #index of max value

5

In [19]:
arr_rand.argmin()  #index of min value

4